//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.12 at 09:02:10 PM BRT 
//


package br.com.cscdesenvolvimento;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountDetail" type="{http://cscdesenvolvimento.com.br}AccountDetail"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accountDetail"
})
@XmlRootElement(name = "GetAccountDetailResponse")
public class GetAccountDetailResponse {

    @XmlElement(name = "AccountDetail", required = true)
    protected AccountDetail accountDetail;

    /**
     * Gets the value of the accountDetail property.
     * 
     * @return
     *     possible object is
     *     {@link AccountDetail }
     *     
     */
    public AccountDetail getAccountDetail() {
        return accountDetail;
    }

    /**
     * Sets the value of the accountDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountDetail }
     *     
     */
    public void setAccountDetail(AccountDetail value) {
        this.accountDetail = value;
    }

}
