//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.11 at 09:27:16 AM BRT 
//


package br.com.cscdesenvolvimento;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.cscdesenvolvimento package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.cscdesenvolvimento
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllAccountDetailResponse }
     * 
     */
    public GetAllAccountDetailResponse createGetAllAccountDetailResponse() {
        return new GetAllAccountDetailResponse();
    }

    /**
     * Create an instance of {@link AccountDetail }
     * 
     */
    public AccountDetail createAccountDetail() {
        return new AccountDetail();
    }

    /**
     * Create an instance of {@link GetAccountDetailRequest }
     * 
     */
    public GetAccountDetailRequest createGetAccountDetailRequest() {
        return new GetAccountDetailRequest();
    }

    /**
     * Create an instance of {@link GetAccountDetailResponse }
     * 
     */
    public GetAccountDetailResponse createGetAccountDetailResponse() {
        return new GetAccountDetailResponse();
    }

}
